### ISSUE TITLE
Gensim bug

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#17]
Ich bin beim Aufräumen auf folgende Funktion gestoßen:

```python
def make_doc2bow_list(sparse_bow):
    """Creates doc2bow_list for gensim.

    Description:
        With this function you can create a doc2bow_list as input for the gensim
        function `get_document_topics()` to show topics for each document.

    Args:
        sparse_bow (DataFrame): DataFrame with term and term frequency by document.

    Returns:
        List of lists containing tuples.
    """
    doc2bow_list = []
    for doc in sparse_bow.index.groupby(sparse_bow.index.get_level_values('doc_id')):
        temp = [(token, count) for token, count in zip(sparse_bow.loc[doc].index, sparse_bow.loc[doc][0])]
        doc2bow_list.append(temp)
    return doc2bow_list

```

Da kommt dann ungefähr so etwas raus: `[[(1, 2), (3, 4)], [(5, 6), (7, 9)]]`, also Tuple mit `type_id` und Häufigkeit im Dokument. Für die Gensim Funktion `get_document_topics()` übergibt man so eine Tuple-Liste, wenn man wissen will, wie die Topics für dieses Dokument verteilt sind.

Ich habe jetzt einfach mal eben beschriebene Listen der `LdaModel`-Klasse von Gensim übergeben, und tada, sehr schöne Topics:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Key 0</th>
      <th>Key 1</th>
      <th>Key 2</th>
      <th>Key 3</th>
      <th>Key 4</th>
      <th>Key 5</th>
      <th>Key 6</th>
      <th>Key 7</th>
      <th>Key 8</th>
      <th>Key 9</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Topic 0</th>
      <td>bulgaren</td>
      <td>serben</td>
      <td>abweisung</td>
      <td>italien</td>
      <td>augustow</td>
      <td>morava</td>
      <td>risch</td>
      <td>montenegriner</td>
      <td>scheitern</td>
      <td>unterseebot</td>
    </tr>
    <tr>
      <th>Topic 1</th>
      <td>abgewiesen</td>
      <td>südlich</td>
      <td>genommen</td>
      <td>franzosen</td>
      <td>geschütze</td>
      <td>juli</td>
      <td>englische</td>
      <td>nördlich</td>
      <td>märz</td>
      <td>feindliche</td>
    </tr>
    <tr>
      <th>Topic 2</th>
      <td>april</td>
      <td>südlich</td>
      <td>juli</td>
      <td>genommen</td>
      <td>englische</td>
      <td>angriff</td>
      <td>feindliche</td>
      <td>italiener</td>
      <td>italienische</td>
      <td>mehrere</td>
    </tr>
    <tr>
      <th>Topic 3</th>
      <td>gedichte</td>
      <td>berliner</td>
      <td>akademie</td>
      <td>berlin</td>
      <td>leben</td>
      <td>obercensurgericht</td>
      <td>geist</td>
      <td>wahrheit</td>
      <td>kaiser</td>
      <td>heilige</td>
    </tr>
    <tr>
      <th>Topic 4</th>
      <td>lassen</td>
      <td>berlin</td>
      <td>stadt</td>
      <td>deutschland</td>
      <td>hiesigen</td>
      <td>art</td>
      <td>zeitung</td>
      <td>scheint</td>
      <td>weise</td>
      <td>wien</td>
    </tr>
    <tr>
      <th>Topic 5</th>
      <td>leipzig</td>
      <td>oesterreich</td>
      <td>deutschland</td>
      <td>wien</td>
      <td>wiener</td>
      <td>weiß</td>
      <td>leipziger</td>
      <td>stadt</td>
      <td>leben</td>
      <td>art</td>
    </tr>
    <tr>
      <th>Topic 6</th>
      <td>kokil</td>
      <td>przemysl</td>
      <td>lorettohöhe</td>
      <td>abteilungen</td>
      <td>dubissa</td>
      <td>abgeschlagen</td>
      <td>chapelle</td>
      <td>neuve</td>
      <td>östlich</td>
      <td>priesterwald</td>
    </tr>
    <tr>
      <th>Topic 7</th>
      <td>april</td>
      <td>frankfurt</td>
      <td>bahn</td>
      <td>schweiz</td>
      <td>ungarische</td>
      <td>si</td>
      <td>verhältnisse</td>
      <td>bürgerkrieg</td>
      <td>indeß</td>
      <td>oper</td>
    </tr>
    <tr>
      <th>Topic 8</th>
      <td>rüben</td>
      <td>monatschrift</td>
      <td>historische</td>
      <td>baumgartner</td>
      <td>rimini</td>
      <td>magdeburg</td>
      <td>pabst</td>
      <td>laune</td>
      <td>menterschweige</td>
      <td>monsignore</td>
    </tr>
    <tr>
      <th>Topic 9</th>
      <td>frankreich</td>
      <td>polen</td>
      <td>presse</td>
      <td>lassen</td>
      <td>preußen</td>
      <td>artikel</td>
      <td>regierung</td>
      <td>weise</td>
      <td>england</td>
      <td>oesterreich</td>
    </tr>
  </tbody>
</table>

Ich weiß nicht wie weit @MHuberFaust mit Gensim gekommen ist, aber das wäre ja die Bestätigung, dass die schlechten Ergebnisse nicht an unserer `sparse_bow` liegen. Da muss irgendwas während der Speicherung nach Matrix Market Format oder beim Einlesen mit `MmCorpus` von Gensim kaputt gehen.

Jetzt bleibt aber noch die Frage, warum die Doc-Topic-Verteilung so komisch ist. Das ist zwar mit so einer `doc2bow`-Liste besser, aber trotzdem noch irgendwie merkwürdig. Wenn man die Gensim Funktion `model.get_document_topics()` verwendet, werden unterschiedlich große Listen mit `topic_id` und der Verteilung zurückgegeben, deswegen sieht die Heatmap so eintönig aus – bei den anderen zwei LDA Implementierungen ist das aber eben überhaupt nicht so:

![heatmap](https://img1.picload.org/image/dgwclocw/index.png)

Die Funktion, die das Doc-Topic DataFrame zurückgibt, macht übrigens auch sowas:
```python
doc_topic = np.zeros((no_of_topics, no_of_docs))
```
was erklärt, warum so viele Nullwerte drinstehen – weil das Modell einfach nicht mehr Werte hergibt, die die Nullwerte ersetzen könnten, warum auch immer.

Bringen dir die Infos was oder wusstest du das sowieso schon, @MHuberFaust?

**Comment by severinsimmler** [comment]
Sollten wir `make_doc2bow_list()` beibehalten, müsste man das auch irgendwie effizienter lösen. Wenn man das ganze Korpus in einer Liste speichert, explodiert ja der Arbeitsspeicher.

**Comment by sinabock** [comment]
@MHuberFaust: Nachdem auch ein Testlauf mit unserem Korpus (grenzboten_sample) und Gensim ('pur') zu schönen Topics führt, entsteht der Fehler wahrscheinlich beim Schreiben der MarketMatrix.

 Bei dem Versuch die selbst erstellte MarketMatrix mit 
`from scipy.io import mmread`
`mminfotest = mmread('Topics/corpus.mm')`

einzulesen, erhält man die Fehlermeldung: 
```'entries' in header is smaller than number of entries```

(Anzahl der Dokumente, max(tokenID) und sum(Count) werden aber richtig berechnet.

Die mit Gensim erstellte MarketMatrix kann problemlos eingelesen werden.

**Comment by MHuberFaust** [comment]
@sinabock: die Gensim-Doku ist an dieser Stelle nicht aktuell. Wohl erst in späteren versionen hinzugekommen ist die Änderung von sum_count zu nonzero_counts oder so.
Ein Fix für unseren Code wäre:
nonzero_counts = len(sparse_bow.index.get_level_values("token_id")) anstatt 
sum_counts = sparse_bow[0].sum()
Im laufe des Nachmittags pushe ich das voraussichtlich.

Möglicherweise hat das aber auch nicht mit deinem Fehler zu tun. Vielen Dank jedenfall für den Tipp! Meine Vermutung ging in Richtung "Probleme beim einlesen".
