### ISSUE TITLE
evalute parse for fn2metadata()

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/Topics#19]
[parse](https://pypi.python.org/pypi/parse/1.8.2) kann Strings anhand von format-strings à la `{author}_{name}.txt` parsen, vllt. als Ersatz für die re-named-groups anschauen

**Comment by MHuberFaust** [comment]
inzwischen [hier](https://github.com/cophi-wue/metadata-toolbox/blob/master/metadata_toolbox/utils.py) umgesetzt.
