### ISSUE TITLE
Bokeh-Fehler in Jupyter notebooks unter Windows

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#21]
Bei der Anzeige von Bokeh in Jupyter notebooks scheint es (zumindest teilweise) zu Problemen unter Windows zu kommen.

Würdest du mal die komplette Fehlermeldung posten, @MaxV92?

**Comment by MaxV92** [comment]
[Fehlermeldung_Bokeh.txt](https://github.com/DARIAH-DE/Topics/files/1446509/Fehlermeldung_Bokeh.txt)

Die Fehlermeldung erschient als "Notebook validation failed - The save operation succeeded, but the notebook does not appear to be valid. The validation error was:" 

@severinsimmler Hoffe du kannst mit der .txt etwas anfangen, für einen Screenshot ist die Meldung zu lang.

**Comment by severinsimmler** [comment]
Danke!

Wie aktuell sind eigentlich deine Pakete? Versuch doch mal bitte in der entsprechenden Kommandozeile `pip freeze` und poste die Ausgabe hier.

**Comment by severinsimmler** [comment]
Du hast:
```
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.1
```

Ich habe:
```
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
```

Update einfach mal mit `pip install --upgrade jupyter` und schau, ob die Fehlermeldung immer noch kommt.

**Comment by MaxV92** [comment]
Also, positiv: die "große Fehlermeldung" wie oben angegeben wird nicht mehr angezeigt. Dafür wird noch eine andere unterhalb der Zelle ausgegeben (siehe Screenshot)...
![bokeh](https://user-images.githubusercontent.com/31919254/32450306-2c51b994-c314-11e7-8326-3308f96e780c.JPG)

**Comment by severinsimmler** [comment]
Ist das immer noch so mit aktuellen Versionen von bokeh und jupyter?
