### ISSUE TITLE
Integration von Java Programmen

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#23]
Ich finde so, wie wir derzeit MALLET aufrufen ist ein bisschen unübersichtlich (da sehr viele Parameter, die zwar alle Default Werte haben, aber ein Blick in die Doku schreckt schon ein bisschen ab).

Würde es Sinn machen, wenn wir eine Funktion `call_java()` oder so schreiben, die `subprocess.Popen(cmd, ...)` enthält? Das wäre generischer, da man so auch andere Java Programme aufrufen kann (z. B. den DKPro-Wrapper).

Macht es Sinn, *alle* MALLET Parameter in der Funktion festzuschreiben, wie wir es aktuell machen? Sollte MALLET irgendwann etwas ändern, funktioniert es bei uns nicht mehr. Stattdessen könnten wir z. B. eine Klasse folgendermaßen aufbauen, die intern `call_java()` aufruft:

```python
class Mallet(path_to_mallet):
    """
    Hier kann dann auch auf für MALLET spezifische Fehlerquellen
    eingegangen werden, z. B. ob es irgendwo Leerzeichen gibt.
    """
    def create_binary(self, cmd=['import-dir', '--input', 'corpus', ...]):
        call_java(cmd)
    def create_model(self, cmd=['train-topics', '--input', 'binary.mallet', ...]):
        call_java(cmd)
```

Erfahrungsgemäß finde ich es übersichtlicher, wenn man eine Liste von Strings mit den MALLET Parametern übergibt, als 40 in der Funktion festgelegte Parameter auf True oder False setzt (was ich ja selber damals so umgesetzt habe).

**Comment by sinabock** [comment]
Also ich finde die Idee prinzipiell gut, frage mich aber, ob das Schreiben und Übergeben einer Liste mit Parametern nicht etwas fehleranfälliger ist. Dachte wir hätten das intern etwas umständlicher gemacht, damit es von außen am Anfang einfacher ist?

**Comment by thvitt** [comment]
Eine Variante, an die ich mal gedacht hatte, ist die Verwendung von kwargs à la

```python
def mallet(command='train-topics', executable='mallet',  **kwargs):
     args = [executable, command]
     for option, value in kwargs:
         args.append("--" + option.replace('_', '-'))
         if value is not None:
              args.append(value)
     # Mallet aufrufen, Fehlerhandling etc.
```

dann kann man pythonesques `mallet(num_topics=10, num_threads=multiprocessing.cpu_count())` schreiben.

**Comment by thvitt** [comment]
Im Prinzip kann man in der Mallet-Klasse ja auch gleich interne Dateien bzw. Pfade dazu wie das `text.vectors`-File verwalten …

**Comment by severinsimmler** [comment]
Dann werde ich mir @thvitt's Vorschlag mal mit @MaxV92 anschauen.

Mit der Fehleranfälligkeit hast du natürlich recht, @sinabock – mit `**kwargs` finde ich das sehr schön gelöst.

**Comment by severinsimmler** [comment]
Bei MALLET ist übrigens `stdout` mit `stderr` vertauscht, jedenfalls bekommen ich mit `stderr` von `Popen` das Logging und von `stdout` Fehlermeldungen.

**Comment by severinsimmler** [comment]
Bis auf #25 vollständig umgesetzt inkl. Docstrings und Doctests.

Eine Klasse `Mallet` mit drei Methoden:
* `call_mallet()` ruft MALLET mit einem spezifischen Kommando + Parameter auf.
* `import_tokenized_corpus()` ruft `self.call_mallet()` mit dem Kommando `import-dir` + Parameter auf.
* `train_topics()` ruft `self.call_mallet()` mit dem Kommando `train-topics` + Parameter auf.

## Error handling
Wenn Leerzeichen in einem Pfad sind, `ValueError`:
https://github.com/DARIAH-DE/Topics/blob/f2187e73f1caeeb30d7d7df664d2a5719c8ee58c/dariah_topics/mallet.py#L115-L135

bzw.

https://github.com/DARIAH-DE/Topics/blob/f2187e73f1caeeb30d7d7df664d2a5719c8ee58c/dariah_topics/mallet.py#L224-L225

Wenn MALLET keine  Ausgabedateien produziert hat, `OSError`:
https://github.com/DARIAH-DE/Topics/blob/f2187e73f1caeeb30d7d7df664d2a5719c8ee58c/dariah_topics/mallet.py#L138-L157
