### ISSUE TITLE
postprocessing.show_doc_topics argument topics not optional

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/Topics#26]
although 'index' is described as optional index.values is called in the first line of the function.
it breaks when the function is called with mallet output.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-7b60d3d73577> in <module>()
      1 
----> 2 doc_topic = postprocessing.show_document_topics(topics=None, model=None, document_labels=None, doc_topics_file='/Users/MHuber/Documents/SS2017/grenzbote_mallet_output_rechenknecht/doc_topics.txt', doc2bow=None, num_keys=3)
      3 doc_topic

/Users/MHuber/git/DariahTopics/dariah_topics/postprocessing.py in show_document_topics(topics, model, document_labels, doc_topics_file, doc2bow, num_keys)
    253     from gensim.models import LdaModel, LdaMulticore
    254 
--> 255     index = [' '.join(keys[:num_keys]) for keys in topics.values]
    256     if isinstance(model, LDA):
    257         return _show_lda_document_topics(model, document_labels, index)

AttributeError: 'NoneType' object has no attribute 'values'

**Comment by thvitt** [comment]
Da fehlt aber der Parameter `topics`, nicht `index`

**Comment by thvitt** [comment]
Der Mallet-Codepath ist nicht getestet, oder? Beim Anschauen sehe ich
* `index` benutzt `topics` auch wenn's fehlt
* `index` benutzt auch wenn's fehlt https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L537
* `columns` undefiniert https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L549

**Comment by thvitt** [comment]
Der Mallet-Codepath ist nicht wirklich getestet, oder? 

* Die o.g. Stelle mit dem `topics.values` wenn topics None ist
* `if index is not None`? https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L537
* columns ist nicht definiert https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L549
* easy_file_format ist möglicherweise nicht definiert https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L533

**Comment by severinsimmler** [comment]
`topics` muss – egal welche LDA Implementierung – immer angegeben werden, da so der Index des Document-Topics-DataFrames gebildet wird (dann müsste dein Funktionsaufruf auch klappen, @MHuberFaust). 

Todo:
* Fehler melden, wenn `topics = None` bzw. Parameter `topics` nicht als optional deklarieren.
* Der letzte `else`-Block macht tatsächlich keinen Sinn, weil `columns` nie definiert wird:
https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L539-L549
* Die Funktion läuft bisher nur, wenn automatisch `easy_file_format` festgestellt wird.
https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L530-L533

**Comment by severinsimmler** [comment]
Was heißt eigentlich `easy_file_format`? Bzw. wann ist es kein `easy_file_format`? Der Code ist aus dem Riddell-Tutorial übernommen.

**Comment by severinsimmler** [comment]
Ah, wenn `if l.startswith('#')`...

**Comment by severinsimmler** [comment]
Sieht eine MALLET Ausgabedatei überhaupt jemals so aus oder ist das ein Überbleibsel aus ganz alten Versionen?
https://github.com/DARIAH-DE/Topics/blob/05dbbaeebca1af736d4a9bd20a0f80466d9a78b7/dariah_topics/postprocessing.py#L518-L529

**Comment by MHuberFaust** [comment]
das ist ein Überbleibsel aus alten Versionen.
