### ISSUE TITLE
Demonstrator ins DARIAH-Repository

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#27]
@pielstroem:

* Download Link für den Demonstrator ins DARIAH-Repository eintragen.
* Eigenes GitHub Repository für den Demonstrator erstellen.

**Comment by schildwaechter** [comment]
Ich hatte es so verstanden, dass ihr ein Binary (zip o.Ä.) zum Download anbieten wollt und hatte vorgeschlagen, dieses in das Repository zu tun, also dann die DOI als Download-Link.
https://repository.de.dariah.eu/doc/services/resolver.html#data
