### ISSUE TITLE
Rename things

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/Topics#3]
Review and improve our historically grown variable names

**Comment by severinsimmler** [comment]
Ich denke gerade über den Funktionsnamen `create_sparse_bow` nach. *Sparse* ist die Matrix eigentlich gar nicht, weil keine einzige Null vorkommt (für jedes Dokument werden ja nur die Worthäufigkeiten geschrieben, die in dem Dokument auch tatsächlich vorkommen).

Das Besondere an der Funktion ist doch die [spezielle Darstellung](http://math.nist.gov/MatrixMarket/formats.html#MMformat) der Zahlenwerte.

Fällt jemandem ein schicker Name ein? `create_matrix_market`? Darunter kann man sich aber irgendwie auch nicht so richtig was vorstellen... Gensim nennt das ganz einfach nur `MmCorpus`. Oder wir bleiben bei `sparse_bow`?

PS: Übrigens sehr verwirrend, weil Gensim teilweise von "Market Matrix" spricht, obwohl es in Wirklichkeit "Matrix Market" heißt. [Laut Entwickler](https://groups.google.com/forum/#!topic/gensim/WdsGE-dFWtE) aber tatsächlich ein Wortdreher.

**Comment by severinsimmler** [comment]
Ich würde es gut finden, wenn "matrix" vorkommt, weil schließlich eine Matrix rauskommt und das andere verfügbare Datenmodell auch `create_document_term_matrix` heißt.

**Comment by severinsimmler** [comment]
Ah! Vielleicht beide Optionen in eine einzige Funktion packen, die `create_document_term_matrix` heißt und wenn `matrix_market=True`, dann Matrix Market Format (für große Korpora) und sonst die klassische Dokument-Term-Matrix?

**Comment by sinabock** [comment]
Ich finde `create_document_term_matrix()` ganz gut, denn in beiden Fällen ist es ja das was wir mappen. "Matrix Market" ist ja nur das Format in dem wir die "Doc-Term-Matrix" konvertieren, um sie dann in Gensim laden zu können. Das könnte dann ja aber auch in der Dokumentation erläutert werden.
