### ISSUE TITLE
Check cophi-toolbox.preprocessing

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/Topics#47]
check if cophi-toolbox.preprocessing == dariah-topics.preprocessing

**Comment by MHuberFaust** [comment]
there is redundancy, but dariah-topics.preprocessing also includes preprocessing functions specifically tailored for topic modelling.
add_token2id
create_document_term_matrix()
read_matrix_market_file()
read_model()
read_token2id()

**Comment by thvitt** [comment]
has there been separate development in the common functions?

**Comment by MHuberFaust** [comment]
nope :)
