### ISSUE TITLE
Zusammenfassen mehrerer Funktionen

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#6]
Macht es Sinn verschiedene Funktionen, die gleiche Dinge mit verschiedenen Dateiformaten machen zusammenzufassen?

Zum Beispiel wird aus:
* `read_from_txt`
* `read_from_tei`
* `read_from_csv`

die Funktion `read_from_file`, die dann ungefähr so aufgebaut ist:

```python
def read_from_file(path):
    if extension == 'txt':
        spezifisches zeug für txt-dateien
    elif extension == 'xml':
        spezifisches zeug für xml-dateien
    elif extension == 'csv':
        spezifisches zeug für csv-dateien
    else:
        dateiformat nicht unterstützt
```

**Comment by severinsimmler** [comment]
So müsste man nicht überlegen in welchem Format das Korpus vorliegt und man könnte Verzeichnisse mit gemischten Dateiformaten auf einmal einlesen.

**Comment by sinabock** [comment]
Hatten wir auch für `remove_features` (arbeitet mit einem DataFrame) und `remove_features_from_file` (arbeitet mit dem MultiIndex) überlegt.

**Comment by thvitt** [comment]
Bei Dateien würde ich nicht zwingend die Unterscheidung nach Dateinamen machen.

```python
def read_from_file(path, format=None):
    if format == 'text' or path.suffix == '.txt':
        …
    else:
        raise ValueError(…)
```

**Comment by severinsimmler** [comment]
Alles klar, dann mache ich das so.

Dann räume ich mal alles, was Features entfernt in eine Funktion, @sinabock? Lässt sich ja mit einem `if isinstance()` schön machen.

**Comment by thvitt** [comment]
wenn das größere Mengen an Code sind, die unterschiedlich sind, würde ich eher separate interne Funktionen (`_foo`)  verwenden und die von der gemeinsamen Frontend-Funktion aufrufen: So bleibt die Gesamtgröße der Funktion überschaubar, die Kapselung gewahrt und man kann offensichtlicher individuelle Tests schreiben.
