### ISSUE TITLE
update example in readme.md

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/Topics#64]
import statement needs changing
maybe add a graphic which is produced out of the 
-> visualization.PlotDocumentTopics.to_file() needs an update

**Comment by MHuberFaust** [comment]
preprocessing.read_files -> read_from_pathlist

**Comment by severinsimmler** [comment]
> maybe a problem with the function name overlap?

Yes, exactly. And someone should update and test the whole module.
