### ISSUE TITLE
README überarbeiten

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/Topics#7]
Derzeit wird im README empfohlen das Repository mit Git zu klonen. Hat das z. B. in Graz irgendjemand so gemacht, @pielstroem?

Vielleicht sollten wir technisch unerfahrenen Nutzern eher nicht empfehlen, noch ein Programm zu installieren, das man vermutlich nie wieder braucht und insgesamt auch eher aufwendig über die Kommandozeile bedienbar ist? Schließlich gibt es direkt auf GitHub eine Downloadfunktion des ZIP-Archivs (auf die man hinweisen könnte) – und ich glaube wenn jemand darauf besteht Git zu benutzen, weiß er auch wie man ein Repository klont!?

**Comment by severinsimmler** [comment]
Vielleicht könnte man das ja so strukturieren:

* Ein Abschnitt mit einer ganz spartanischen, plattformunabhängigen Anleitung (ZIP-Archiv downloaden, entpacken, `cd Topics` und wie man die Abhängigkeiten installiert).
* Ein Abschnitt für Troubleshooting, in dem für jedes Betriebssystem spezifische Probleme behandelt werden (zu denen auch Sachen wie "Wir empfehlen WinPython" zählen könnten).

**Comment by thvitt** [comment]
(Wollten wir nicht eh Anaconda anschauen?)

**Comment by sinabock** [comment]
Anaconda ist im Hinblick Projektverwaltung benutzerfreundlicher (Projekte müssen nicht wie bei WinPython innerhalb eines bestimmten Unterorders liegen, um ausgeführt werden zu können). 

Anaconda konnte auf Linux, MacOs und Windows vergleichbar einfach installiert werden, allerdings darf der Installationspfad für Anaconda unter Windows kein Leerzeichen enthalten, da dies sonst zu Fehlern führt. 

In Anaconda verwendete Pakete (z.B. Spyder) sollten generell nicht mittels  `pip `, sondern in Form von conda-packages installiert werden, da es sonst ebenfalls zu Fehlern kommen kann.

Vielleicht sollten wir Anaconda empfehlen, aber WinPython zumindest als Alternative nennen?

**Comment by severinsimmler** [comment]
`pip install git+https://github.com/DARIAH-DE/Topics.git`

**Comment by severinsimmler** [comment]
# Aktualisierung

Überarbeitet werden müsste der Abschnitt **Working with notebooks** inkl. Troubleshooting und allem, was hier schon beschrieben wurde.

**Comment by severinsimmler** [comment]
Fürs Troubleshooting:

Wenn mit `pip install git+https...` folgendes bei Linux (dann wohl auch bei macOS): `PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/dariah_topics-0.3.0.dev0-py3.6.egg-info'`, dann braucht man `sudo pip install git+https...`.
