### ISSUE TITLE
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

### ISSUE THREAD

**Issue by BehemothTheCat** [DARIAH-DE/Topics#80]
Folgender Fehler beim Ausführen des Notebooks 2-advanced, part 1:
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

nach dieser Zeile: 
model.fit(dtm)

![1](https://user-images.githubusercontent.com/44614662/58252259-f65d7680-7d65-11e9-82c6-28679ed79032.PNG)
![2](https://user-images.githubusercontent.com/44614662/58252260-f65d7680-7d65-11e9-9998-7488bd9ec0f0.PNG)

**Comment by severinsimmler** [comment]
Vielen Dank für den Hinweis!

Auf welches MALLET Executable wird denn mit dem `mallet` Argument verwiesen? Soweit ich weiß gibt es in dem `mallet/bin` Ordner ein Executable für UNIX-basierte Systeme (`mallet/bin/mallet`) und ein Executable für Windows (`mallet/bin/mallet.bat`). Ich könnte mir vorstellen, dass dieses Problem nicht mehr auftaucht, wenn man den Pfad zu `mallet.bat` angibt?

**Comment by severinsimmler** [comment]
Das heißt:

```python
dariah.core.LDA(num_topics=10,
                num_iterations=1000,
                mallet="mallet-2.0.8/bin/mallet.bat")
```

**Comment by BehemothTheCat** [comment]
Vielen Dank, das hat das Problem gelöst! :)
